EXPLAIN ANALYZE SELECT DISTINCT SKNOM 
FROM SKIPPERS s 
JOIN CROISIERES c ON s.SKNUM = c.SKNUM 
JOIN BATEAUX b ON c.BATNUM = b.BATNUM 
WHERE b.CAPACITE < ALL ( 
    SELECT CAPACITE 
    FROM BATEAUX 
    WHERE BATPORT = 'Ajaccio' 
); 

EXPLAIN ANALYZE SELECT s.sknum
FROM skippers AS s
JOIN croisieres AS c ON s.sknum = c.sknum
JOIN bateaux AS b ON b.batnum = c.batnum
WHERE b.capacite < (
  SELECT MIN(b2.capacite)
  FROM bateaux AS b2
  WHERE b2.batport = 'AJACCIO'
);


EXPLAIN ANALYZE SELECT DISTINCT SKNOM 
FROM CROISIERES 
         NATURAL JOIN SKIPPERS 
WHERE BATNUM IN ( 
    SELECT BATNUM 
    FROM BATEAUX 
    WHERE CAPACITE < ( 
        SELECT MIN(CAPACITE) 
        FROM BATEAUX 
        WHERE BATPORT = 'AJACCIO' 
    ) 
); 
